name: Deploy

on:
  workflow_dispatch:

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: srv
      REGISTRY: ghcr.io/${{ github.actor }}
      CONTAINER_NAME: srv-container

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
  
            echo "Pulling latest image..."
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

            echo "Stopping old container if exists..."
            docker stop ${{ env.CONTAINER_NAME }} || true
            docker rm ${{ env.CONTAINER_NAME }} || true

            echo "Starting new container..."
            docker run -d \
              -e JAVA_OPTS='-Xmx256m' \
              --name ${{ env.CONTAINER_NAME }} \
              -p 8090:8090 \
              ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
